### ISSUE TITLE
Error with is_near_target method?

### ISSUE THREAD

**Issue by honnigmelone** [heyitsalina/ant_search_algorithm#119]
I noticed a mistake with the is_near_target() method related to the try_carry_food and try_drop_food methods. The issue is that is_near_target() only returns true when we artificially add the center_offset value to the ant's coordinates. Without adding these extra values, the method doesn't return true, which makes try_carry_food not work as expected. This leads to incorrect positioning of the ant relative to the food when determining if it's close enough to carry food.

For the tests of try_carry_food and try_drop_food to pass, I had to add +45 to each of the ant's coordinates for now. We need to find a solution to this so we can remove the adjustment.

Let me know if this is clear. I'm not sure of the best solution yet. And please let me know if it really is an error or i am not understanding something correctly

I mean our simulation is working but i still wanted to share this.
(ps. i forgot to mention this in the meeting today. so here is what i wrote once in an earlier pull request)

**Comment by AlhaririAnas** [comment]
In our GUI, when food is placed on the canvas area, the photo is positioned so that its coordinate origin (bottom left) is at the clicked location. Therefore, a center offset, known as center_offset, needs to be added. This can be automated by halving the size of the photo.

For our food photo of 100x100 dimensions, the center_offset is therefore 50. The radius can also be automated.

```python
def draw_food(self):
    with self.canvas:
        for food in sim.food:
            Image(source="../images/apple.png", pos=food.coordinates, size=(100, 100))
```

We chose 45 for the center_offset because it's more precise for the shape of the apple, though 50 would also work.

It would be convenient if the center_offset and radius were automatically calculated and passed to the method. However, this isn't strictly necessary since we only have two types of images: apple and colony.

![20240214-1151-53 8440076-ezgif com-video-to-gif-converter](https://github.com/heyitsalina/ant_search_algorithm/assets/147917604/197f711a-b94d-457d-bfc2-a8e3831e91fa)

I hope this answer clarifies the issue. Otherwise, feel free to ask any questions regarding this.

**Comment by honnigmelone** [comment]
firstly, thanks for the detailed explanation :) I now understand the offset and how it's calculated. 

but is it good that we need to test the method with the ant coordinate +45? I mean it makes sense because then the ant is in the center of the food object actually. But is that a good way to do it? 

<img width="622" alt="image" src="https://github.com/heyitsalina/ant_search_algorithm/assets/147641247/85ff8fdf-a340-45bb-911e-29e6067d73d6">

**Comment by AlhaririAnas** [comment]
> but is it good that we need to test the method with the ant coordinate +45? I mean it makes sense because then the ant is in the center of the food object actually. But is that a good way to do it?

Yes, it's a good way to test if the ant is near the food. It doesn't have to be exactly +45, something like +40 or +55 would also work. The important thing is that the ant is within the food's radius. If your question is answered, you can close the issue :)
