### ISSUE TITLE
Define method move (class Ant)

### ISSUE THREAD

**Issue by tis22** [heyitsalina/ant_search_algorithm#21]
Create a basic movement for the ants.
Test it by using f.e. a plot (start coordinates, coordinates after the movement).

Two ideas from the meeting:
1. A mathematical function (start_pos, target_pos)
2. Directions for a smoother mooving (8 directions)

**Comment by heyitsalina** [comment]
since i wasn`t able to stay for the whole group meeting: do you mean by this that we all create some sort of move method based on our own ideas and then present it to the others next week? So that we can compare each method to one another and then choose the one that fits the best?
just asking to fill in the gaps 🌝

**Comment by honnigmelone** [comment]
other ideas now: to have a direction and move method that an ant is moving steps toward a direction. And the direction can change.

**Comment by AlhaririAnas** [comment]
I am working on move method now!
