### ISSUE TITLE
Implementation of pheromone reduction method in Pheromone Class

### ISSUE THREAD

**Issue by AlhaririAnas** [heyitsalina/ant_search_algorithm#77]
- Implement the `reduce_pheromone()` method in the Pheromone class.
- The method should check if any pheromone's timestamp in `self.timestamps` has reached `k_sec`.
- Upon reaching` k_sec`, the index of the corresponding pheromone should be identified.
- At this index, the pheromone's value in `self.pheromones` should be reduced by the `reducing_factor`.
- After reduction, a new current timestamp should be set at the same position in `self.timestamps`, unless the pheromone value has been reduced to 0.

Note: The method should **continuously** run as long as there are pheromones present in the ant world.

**_The implementation approach can be modified or rethought as this is an initial proposal._**

**Comment by tis22** [comment]
Here are the results of our meeting earlier:
If the method continuously runs this _could_ lead to inconsistent behavior (update status of a pheromone by addition, update status by multiplication), therefore I'm trying to implement an method which updates the pheromones every epoch.

To determine the time passed my approch is to create a time-delta via the "old" timestamp (f.e. epoch 1) and the "new" timestamp (f.e. epoch 2).

**Comment by tis22** [comment]
In our todays meeting we decided to alter the commited code-idea #[3020221](https://github.com/heyitsalina/ant_search_algorithm/commit/30202215d1876d53cd6335defe780719692aa4f0) .

There are two possible easier reduction methods:

1. Muliply the whole matrix with a reduction factor every epoch.
- Pheromones which are 0 will stay 0
- Pheromones != 0 will be reduced over time
- By the multiplication these will be reduced weighted by their amount (higher amount of pheromones = higher reduction)
$\ 5 * 0.5 = 2.5$ 
(reduction of -2.5)
$\ 2 * 0.5 = 1$ 
(reduction of -1)
- decide for a limit from which the value is considered 0, round
(because of the multiplication the values never become completely 0, but rather approach 0)

==> This reflects the natural decrease better.


2. Subtract the pheromone-values constantly by a value
- If an element in the array is != 0 it will be updated every epoch
- This doesn't take into account when the pheromone was placed
f.e. 
pheromone is 5:
epoch -> 5-0.5 = 4.5
next epoch -> 4.5 - 0.5 = 4




Because of this implementations we don't need the time-module and the timestamps-arrays anymore ==> remove.
